name = "CircuitConstants"
uuid = "466811a3-3058-4698-aa42-3b1fb407388b"
authors = ["Glen Hertz <glen.hertz@gmail.com>"]
version = "0.9.0"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]